server: 
  port: 4001 
   
spring: 
  application: 
    name: microservice-config-test
  cloud: 
    config: 
      server: 
        git: 
          uri: https://github.com/nobt854/testSpringCloudConfig
